name: pt_next
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/sql/init.sql
     - assets/dll/sqlite3.dll

  fonts:
   - family: WenKaiScreen
     fonts:
       - asset: assets/fonts/LXGWWenKaiScreen.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
